import { CaptionPreset, CaptionStyleConfig, Clip, Project } from '../types/editor';

export const CAPTION_PRESETS: Record<CaptionPreset, CaptionStyleConfig> = {
  viral: {
    preset: 'viral',
    fontFamily: "'Montserrat', sans-serif",
    fontSize: 18,
    textColor: '#ffffff',
    highlightColor: '#22c55e', // Neon green
    strokeColor: '#000000',
    strokeWidth: 3,
    bgColor: '#eab308', // Gold/yellow
    hasBackground: false,
    uppercase: true,
    positionY: 74,
    animation: 'bounce',
  },
  minimal: {
    preset: 'minimal',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: 15,
    textColor: '#f8fafc',
    highlightColor: '#38bdf8', // Sky blue
    strokeColor: '#000000',
    strokeWidth: 2,
    bgColor: 'rgba(0,0,0,0.65)',
    hasBackground: true,
    uppercase: false,
    positionY: 76,
    animation: 'fade',
  },
  podcast: {
    preset: 'podcast',
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 20,
    textColor: '#ffffff',
    highlightColor: '#f97316', // Orange
    strokeColor: '#090b10',
    strokeWidth: 3.5,
    bgColor: '#1e293b',
    hasBackground: false,
    uppercase: true,
    positionY: 72,
    animation: 'pop',
  },
  gamer: {
    preset: 'gamer',
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 17,
    textColor: '#e0f2fe',
    highlightColor: '#06b6d4', // Cyan
    strokeColor: '#a855f7', // Purple
    strokeWidth: 2.5,
    bgColor: '#020617',
    hasBackground: true,
    uppercase: true,
    positionY: 75,
    animation: 'glow',
  },
  premium: {
    preset: 'premium',
    fontFamily: "'Plus Jakarta Sans', serif",
    fontSize: 16,
    textColor: '#fef08a', // Light gold
    highlightColor: '#fbbf24', // Gold
    strokeColor: '#171717',
    strokeWidth: 2,
    bgColor: 'rgba(15,23,42,0.85)',
    hasBackground: true,
    uppercase: false,
    positionY: 78,
    animation: 'pop',
  },
  impact: {
    preset: 'impact',
    fontFamily: "'Montserrat', sans-serif",
    fontSize: 19,
    textColor: '#ffffff',
    highlightColor: '#ef4444', // Red
    strokeColor: '#000000',
    strokeWidth: 4,
    bgColor: '#000000',
    hasBackground: false,
    uppercase: true,
    positionY: 70,
    animation: 'bounce',
  },
};

// Reliable open MP4 video for live demonstrations
export const SAMPLE_VIDEO_URL =
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4';

export const INITIAL_SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj-01',
    name: 'Podcast Inovação & Riqueza #42',
    createdAt: 'Hoje às 14:30',
    status: 'analyzed',
    clipsCount: 5,
    videoMetadata: {
      id: 'vid-01',
      name: 'Entrevista_Ep42_Final_4K.mp4',
      duration: 184, // ~3 minutes
      resolution: '1920x1080 (16:9)',
      fileSizeFormatted: '142.8 MB',
      fps: 60,
      url: SAMPLE_VIDEO_URL,
      thumbnailUrl:
        'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80',
    },
    clips: [
      {
        id: 'clip-01',
        projectId: 'proj-01',
        title: 'NINGUÉM TE CONTA ISSO SOBRE DINHEIRO',
        startTime: 12,
        endTime: 44,
        duration: 32,
        viralScore: 98,
        viralTag: 'Hook Magnético 🔥',
        whyViral:
          'Possui uma afirmação forte nos primeiros 3 segundos e apresenta uma mudança de assunto que eleva a taxa de retenção média acima de 85%.',
        viralityHooks: [
          'Gancho nos primeiros 2s',
          'Quebra de expectativa',
          'Alta cadência verbal',
        ],
        fullText:
          'A maioria das pessoas passa 40 anos trabalhando pelo dinheiro, mas nunca entende que o segredo não é quanto você ganha, e sim quanto do seu tempo você recompra. Se você não tem tempo, você é apenas um escravo com salário melhor.',
        transcript: [
          { word: 'A', start: 12.0, end: 12.3 },
          { word: 'maioria', start: 12.3, end: 12.9 },
          { word: 'das', start: 12.9, end: 13.1 },
          { word: 'pessoas', start: 13.1, end: 13.7 },
          { word: 'passa', start: 13.7, end: 14.1 },
          { word: '40', start: 14.1, end: 14.6 },
          { word: 'anos', start: 14.6, end: 15.0 },
          { word: 'trabalhando', start: 15.0, end: 15.9 },
          { word: 'pelo', start: 15.9, end: 16.2 },
          { word: 'dinheiro,', start: 16.2, end: 17.0 },
          { word: 'mas', start: 17.4, end: 17.7 },
          { word: 'nunca', start: 17.7, end: 18.2 },
          { word: 'entende', start: 18.2, end: 18.8 },
          { word: 'que', start: 18.8, end: 19.0 },
          { word: 'o', start: 19.0, end: 19.2 },
          { word: 'segredo', start: 19.2, end: 19.8 },
          { word: 'não', start: 19.8, end: 20.2 },
          { word: 'é', start: 20.2, end: 20.4 },
          { word: 'quanto', start: 20.4, end: 20.9 },
          { word: 'você', start: 20.9, end: 21.3 },
          { word: 'ganha,', start: 21.3, end: 22.0 },
          { word: 'e', start: 22.4, end: 22.6 },
          { word: 'sim', start: 22.6, end: 23.0 },
          { word: 'quanto', start: 23.0, end: 23.5 },
          { word: 'do', start: 23.5, end: 23.7 },
          { word: 'seu', start: 23.7, end: 24.0 },
          { word: 'tempo', start: 24.0, end: 24.6 },
          { word: 'você', start: 24.6, end: 25.0 },
          { word: 'recompra.', start: 25.0, end: 26.2 },
          { word: 'Se', start: 27.0, end: 27.3 },
          { word: 'você', start: 27.3, end: 27.6 },
          { word: 'não', start: 27.6, end: 28.0 },
          { word: 'tem', start: 28.0, end: 28.4 },
          { word: 'tempo,', start: 28.4, end: 29.2 },
          { word: 'você', start: 29.8, end: 30.2 },
          { word: 'é', start: 30.2, end: 30.4 },
          { word: 'apenas', start: 30.4, end: 31.0 },
          { word: 'um', start: 31.0, end: 31.3 },
          { word: 'escravo', start: 31.3, end: 32.1 },
          { word: 'com', start: 32.1, end: 32.4 },
          { word: 'salário', start: 32.4, end: 33.2 },
          { word: 'melhor.', start: 33.2, end: 34.5 },
        ],
        framingMode: 'auto',
        zoomEffect: true,
        silenceRemoved: true,
        speed: 1.0,
        volume: 1.0,
        filter: 'clean',
        captionStyle: CAPTION_PRESETS.viral,
        titleAi: 'NINGUÉM TE CONTA ISSO SOBRE DINHEIRO',
        descriptionAi:
          'Uma reflexão visceral sobre tempo vs salário que pode mudar a forma como você enxerga riqueza e liberdade financeira.',
        hashtagsAi: [
          '#dinheiro',
          '#mindset',
          '#empreendedorismo',
          '#liberdade',
          '#cortes',
          '#tiktokbrasil',
        ],
      },
      {
        id: 'clip-02',
        projectId: 'proj-01',
        title: 'O MAIOR ERRO DE QUEM COMEÇA UM NEGÓCIO',
        startTime: 48,
        endTime: 93,
        duration: 45,
        viralScore: 94,
        viralTag: 'Alta Curiosidade ⚡',
        whyViral:
          'Identificou pergunta provocativa seguida de revelação contra-intuitiva com pico de entonação emocional.',
        viralityHooks: ['Pergunta e Resposta', 'Conflito de opiniões', 'Dica prática'],
        fullText:
          'O erro número um é querer criar o produto perfeito antes de conversar com dez clientes reais. Quem gasta meses fechado no quarto programando sem validar antes está construindo um monumento ao próprio ego.',
        transcript: [
          { word: 'O', start: 48.0, end: 48.3 },
          { word: 'erro', start: 48.3, end: 48.8 },
          { word: 'número', start: 48.8, end: 49.3 },
          { word: 'um', start: 49.3, end: 49.8 },
          { word: 'é', start: 49.8, end: 50.1 },
          { word: 'querer', start: 50.1, end: 50.6 },
          { word: 'criar', start: 50.6, end: 51.2 },
          { word: 'o', start: 51.2, end: 51.4 },
          { word: 'produto', start: 51.4, end: 52.0 },
          { word: 'perfeito', start: 52.0, end: 52.8 },
          { word: 'antes', start: 53.0, end: 53.4 },
          { word: 'de', start: 53.4, end: 53.6 },
          { word: 'conversar', start: 53.6, end: 54.4 },
          { word: 'com', start: 54.4, end: 54.7 },
          { word: 'clientes', start: 54.7, end: 55.4 },
          { word: 'reais.', start: 55.4, end: 56.5 },
        ],
        framingMode: 'auto',
        zoomEffect: true,
        silenceRemoved: false,
        speed: 1.0,
        volume: 1.0,
        filter: 'vibrant',
        captionStyle: CAPTION_PRESETS.impact,
        titleAi: 'O MAIOR ERRO DE QUEM COMEÇA UM NEGÓCIO',
        descriptionAi:
          'Se você está criando um produto agora, pare tudo e assista isso antes de perder meses da sua vida.',
        hashtagsAi: ['#negocios', '#startup', '#marketing', '#empreender', '#foco'],
      },
      {
        id: 'clip-03',
        projectId: 'proj-01',
        title: 'A REGRA DOS 15 MINUTOS PARA FOCO TOTAL',
        startTime: 100,
        endTime: 160,
        duration: 60,
        viralScore: 91,
        viralTag: 'Formato Educativo 💡',
        whyViral:
          'Passo a passo acionável com storytelling envolvente e alto compartilhamento entre estudantes e profissionais.',
        viralityHooks: ['Método simples', 'Relevância imediata', 'Alta retenção'],
        fullText:
          'Sempre que a preguiça bater, diga ao seu cérebro que você só vai fazer por quinze minutos. Se quiser parar depois, está liberado. Mas noventa por cento das vezes a inércia é quebrada e você continua.',
        transcript: [
          { word: 'Sempre', start: 100.0, end: 100.6 },
          { word: 'que', start: 100.6, end: 100.8 },
          { word: 'a', start: 100.8, end: 101.0 },
          { word: 'preguiça', start: 101.0, end: 101.8 },
          { word: 'bater,', start: 101.8, end: 102.5 },
          { word: 'diga', start: 102.8, end: 103.2 },
          { word: 'ao', start: 103.2, end: 103.4 },
          { word: 'seu', start: 103.4, end: 103.7 },
          { word: 'cérebro...', start: 103.7, end: 104.8 },
        ],
        framingMode: 'center',
        zoomEffect: false,
        silenceRemoved: true,
        speed: 1.0,
        volume: 1.0,
        filter: 'cinematic',
        captionStyle: CAPTION_PRESETS.podcast,
        titleAi: 'A REGRA DOS 15 MINUTOS PARA FOCO TOTAL',
        descriptionAi:
          'Como vencer a procrastinação usando esse truque psicológico simples e cientificamente validado.',
        hashtagsAi: ['#produtividade', '#foco', '#estudos', '#disciplina', '#hacks'],
      },
    ],
  },
];
